/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class cuasoDiemPB extends javax.swing.JPanel {

    /**
     * Creates new form viewdiem
     */
    DefaultTableModel defaultTableModel;
    public cuasoDiemPB() {
        initComponents();
        show();
    }
    public void loadcbbma(String magv){
        Connection ketNoi = DBConnection.getConnection();
        String sql = "SELECT madoan from ct_doan where magvpb='"+magv+"' order by madoan";
        jcbbmadoanpb.removeAllItems();

        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jcbbmadoanpb.addItem(rs.getString("madoan"));

            }
            rs.close();
            ps.close();
            ketNoi.close();

        } catch (SQLException e) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }


    public void show(){
        defaultTableModel = new DefaultTableModel();
        bangDS.setEditingColumn(0);
        bangDS.setEditingRow(0);
        String ma= (String) GiangVien_Form.ma;
        loadcbbma(ma);
        defaultTableModel.addColumn("MÃ ĐỒ ÁN");
        defaultTableModel.addColumn("MÃ SINH VIÊN");
        defaultTableModel.addColumn("MÃ GIẢNG VIÊN PHẢN BIỆN");
        defaultTableModel.addColumn("ĐIỂM PHẢN BIỆN");
        ArrayList<chamdiemPB> list= ThaoTacGV.getTableChamDPB();
        for(chamdiemPB k: list){
            defaultTableModel.addRow(k.toObjectsdPB());
        }
        bangDS.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfDPB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangDS = new javax.swing.JTable();
        jButtonLuu = new javax.swing.JButton();
        jLabeltbPB = new javax.swing.JLabel();
        jcbbmadoanpb = new javax.swing.JComboBox<>();

        jLabelTb.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelTb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Mã đồ án:");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Điểm:");
        jLabel2.setOpaque(true);

        jtfDPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDPBActionPerformed(evt);
            }
        });

        bangDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bangDS);

        jButtonLuu.setText("LƯU");
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuuActionPerformed(evt);
            }
        });

        jLabeltbPB.setBackground(new java.awt.Color(255, 204, 255));
        jLabeltbPB.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabeltbPB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltbPB.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDPB, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jcbbmadoanpb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(jButtonLuu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabeltbPB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbbmadoanpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLuu))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jLabeltbPB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDPBActionPerformed

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuuActionPerformed
        String MaDA=String.valueOf(jcbbmadoanpb.getSelectedItem().toString().trim()) ;
        String temp=jtfDPB.getText().trim().toString();
        String check="[0-9]{1,2}+.+[0-9]{1,2}";
        String check1="[0-9]{1,2}";
        if(MaDA.equals("")){
            jLabeltbPB.setText("Bạn chưa nhập mã đồ án!");
            jLabeltbPB.setVisible(true);
            return;
        }
        if(temp.equals("")){
            jLabeltbPB.setText("Bạn chưa nhập điểm!");
            jLabeltbPB.setVisible(true);
            return;
        }
        if(!temp.matches(check)){
            if(!temp.matches(check1)){
                jLabeltbPB.setText("Điểm không đúng định dạng!");
                jLabeltbPB.setVisible(true);
            return;
            }
        }
        float DiemPB=Float.parseFloat(temp);
        if(DiemPB>10){
           jLabeltbPB.setText("Điểm không đúng định dạng!");
           jLabeltbPB.setVisible(true);
            return;
        }
        chamdiemPB cd= new chamdiemPB(MaDA, MaDA, MaDA, DiemPB);
        jLabeltbPB.setVisible(false);
        if(ThaoTacGV.ktMaDoAn(MaDA)){
//            if(ThaoTacGV.ktDKDiemHD(ThaoTacGV.layDHD(MaDA))){
//               if(ThaoTacGV.ktTTDiemPB(ThaoTacGV.layDPB(MaDA))){
               int k=JOptionPane.showConfirmDialog(this,"Bạn có muốn cập nhật điểm không", "Cảnh báo", JOptionPane.YES_NO_OPTION);
               if(k==0){
                   ThaoTacGV.suaDiemPB(cd);
                   show();
               }
//           }
//           else{
//               int h= JOptionPane.showConfirmDialog(this,"Bạn có muốn lưu điểm không?" , "Cảnh Báo", JOptionPane.YES_NO_OPTION);
//               if(h==0){
//                   ThaoTacGV.suaDiemPB(cd);
//                   show();
//                }
//           } 
//           }
//            else{
//                JOptionPane.showMessageDialog(this,"Sinh viên không đạt điều kiện!");
//            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Mã đồ án không tồn tại!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLuuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangDS;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTb;
    private javax.swing.JLabel jLabeltbPB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbbmadoanpb;
    private javax.swing.JTextField jtfDPB;
    // End of variables declaration//GEN-END:variables
}
