/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class cuasoDiemTieuBan extends javax.swing.JPanel {

    /**
     * Creates new form viewdiemHD
     */
    DefaultTableModel defaultTableModel;
    public cuasoDiemTieuBan() {
        initComponents();
        show();
    }

    public void loadcbbma(String magv){
        Connection ketNoi = DBConnection.getConnection();
        String sql = "SELECT ct_doan.madoan from ct_doan, (select matieuban from ct_tieuban where magv='"+magv+"') AS A where ct_doan.matieuban=A.matieuban order by madoan";
        jcbbmadoantb.removeAllItems();

        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jcbbmadoantb.addItem(rs.getString("madoan"));

            }
            rs.close();
            ps.close();
            ketNoi.close();

        } catch (SQLException e) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public void show(){
        defaultTableModel = new DefaultTableModel();
        bangDS.setEditingColumn(0);
        bangDS.setEditingRow(0);
        String ma= (String) GiangVien_Form.ma;
        loadcbbma(ma);
        defaultTableModel.addColumn("MÃ ĐỒ ÁN");
        defaultTableModel.addColumn("MÃ SINH VIÊN");
        defaultTableModel.addColumn("MÃ TIÊU BAN");
        defaultTableModel.addColumn("MÃ GIẢNG VIÊN");
        defaultTableModel.addColumn("ĐIỂM TIỂU BAN");
        ArrayList<chamdiemTB> list =ThaoTacGV.getTableChamDiemTB();
        for(chamdiemTB k: list){
            defaultTableModel.addRow(k.toObjectsdTB());
        }
        bangDS.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfDTB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangDS = new javax.swing.JTable();
        jButtonLuu = new javax.swing.JButton();
        jLabeltbTB = new javax.swing.JLabel();
        jcbbmadoantb = new javax.swing.JComboBox<>();

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Mã đồ án:");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Điểm:");
        jLabel2.setOpaque(true);

        jtfDTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDTBActionPerformed(evt);
            }
        });

        bangDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bangDS);

        jButtonLuu.setText("LƯU");
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuuActionPerformed(evt);
            }
        });

        jLabeltbTB.setBackground(new java.awt.Color(255, 204, 255));
        jLabeltbTB.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabeltbTB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltbTB.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDTB, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jcbbmadoantb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(jButtonLuu)
                        .addGap(0, 340, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabeltbTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbbmadoantb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLuu))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(72, 72, 72)
                .addComponent(jLabeltbTB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDTBActionPerformed

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuuActionPerformed
        String MaDA=String.valueOf(jcbbmadoantb.getSelectedItem().toString().trim()) ;
        String temp=jtfDTB.getText().trim().toString();
        String check="[0-9]{1,2}+.+[0-9]{1,2}";
        String check1="[0-9]{1,2}";
        if(MaDA.equals("")){
            jLabeltbTB.setText("Bạn chưa nhập mã đồ án!");
            jLabeltbTB.setVisible(true);
            return;
        }
        if(temp.equals("")){
            jLabeltbTB.setText("Bạn chưa nhập điểm!");
            jLabeltbTB.setVisible(true);
            return;
        }
        if(!temp.matches(check)){
            if(!temp.matches(check1)){
                jLabeltbTB.setText("Điểm không đúng định dạng!");
                jLabeltbTB.setVisible(true);
            return;
            }
        }
        float DiemTB=Float.parseFloat(temp);
        if(DiemTB>10){
           jLabeltbTB.setText("Điểm không đúng định dạng!");
           jLabeltbTB.setVisible(true);
            return;
        }
        chamdiemTB cd= new chamdiemTB(MaDA, MaDA, MaDA, MaDA, DiemTB);
        chamdiemPB dpb =new chamdiemPB();
        jLabeltbTB.setVisible(false);
        if(ThaoTacGV.ktMaDoAn(MaDA)){
//            if(ThaoTacGV.ktDKDiemPB(ThaoTacGV.layDPB(MaDA))){
               int k=JOptionPane.showConfirmDialog(this,"Bạn có muốn cập nhật điểm không", "Cảnh báo", JOptionPane.YES_NO_OPTION);
               if(k==0){
                   ThaoTacGV.suaDiemTB(cd);
                   show();
               } 
           }
//            else{
//                JOptionPane.showMessageDialog(this,"Sinh viên không đạt điều kiện!");
//            }
//        }
        else{
            JOptionPane.showMessageDialog(this,"Mã đồ án không tồn tại!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLuuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangDS;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabeltbTB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbbmadoantb;
    private javax.swing.JTextField jtfDTB;
    // End of variables declaration//GEN-END:variables
}
