/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class cuasoDiemHD extends javax.swing.JPanel {

    /**
     * Creates new form viewdiem
     */
    DefaultTableModel defaultTableModel;
    
    
    public cuasoDiemHD() {
        initComponents();
        show();
    }

    public void loadcbbma(String magv){
        Connection ketNoi = DBConnection.getConnection();
        String sql = "SELECT madoan from ct_doan where magvhd='"+magv+"' order by madoan";
        
        jcbbmadoanhd.removeAllItems();
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jcbbmadoanhd.addItem(rs.getString("madoan"));

            }
            rs.close();
            ps.close();
            ketNoi.close();

        } catch (SQLException e) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }
        

    public void show(){
        defaultTableModel = new DefaultTableModel();
        bangDS.setEditingColumn(0);
        bangDS.setEditingRow(0);
        String ma= (String) GiangVien_Form.ma;
        loadcbbma(ma);
        defaultTableModel.addColumn("MÃ ĐỒ ÁN");
        defaultTableModel.addColumn("MÃ SINH VIÊN");
        defaultTableModel.addColumn("MÃ GIẢNG VIÊN HƯỚNG DẪN");
        defaultTableModel.addColumn("ĐIỂM HƯỚNG DẪN");
        ArrayList<chamdiemHD> list =ThaoTacGV.getTableChamDHD();
        for(chamdiemHD k: list){
            defaultTableModel.addRow(k.toObjectsdHD());
        }
        bangDS.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfDHD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangDS = new javax.swing.JTable();
        jButtonLuu = new javax.swing.JButton();
        jLabeltbHD = new javax.swing.JLabel();
        jcbbmadoanhd = new javax.swing.JComboBox<>();

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Mã đồ án:");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Điểm:");
        jLabel2.setOpaque(true);

        jtfDHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDHDActionPerformed(evt);
            }
        });

        bangDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bangDS);

        jButtonLuu.setText("LƯU");
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuuActionPerformed(evt);
            }
        });

        jLabeltbHD.setBackground(new java.awt.Color(255, 204, 255));
        jLabeltbHD.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabeltbHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltbHD.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeltbHD, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDHD)
                            .addComponent(jcbbmadoanhd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jButtonLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbbmadoanhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLuu))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jLabeltbHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDHDActionPerformed

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuuActionPerformed
        String MaDA=String.valueOf(jcbbmadoanhd.getSelectedItem().toString().trim()) ;
        String temp=jtfDHD.getText().trim().toString();
        String check="[0-9]{1,2}+.+[0-9]{1,2}";
        String check1="[0-9]{1,2}";
        if(MaDA.equals("")){
            jLabeltbHD.setText("Bạn chưa nhập mã đồ án!");
            jLabeltbHD.setVisible(true);
            return;
        }
        if(temp.equals("")){
            jLabeltbHD.setText("Bạn chưa nhập điểm!");
            jLabeltbHD.setVisible(true);
            return;
        }
        if(!temp.matches(check)){
            if(!temp.matches(check1)){
                jLabeltbHD.setText("Điểm không đúng định dạng!");
                jLabeltbHD.setVisible(true);
            return;
            }
        }
        float DiemHD=Float.parseFloat(temp);
        if(DiemHD>10){
           jLabeltbHD.setText("Điểm không đúng định dạng!");
           jLabeltbHD.setVisible(true);
            return;
        }
        chamdiemHD cd= new chamdiemHD(MaDA, MaDA, MaDA, DiemHD);
        jLabeltbHD.setVisible(false);
        if(ThaoTacGV.ktMaDoAn(MaDA)){
//           if(ThaoTacGV.ktTTDiemHD(ThaoTacGV.layDHD(MaDA))){
               int k=JOptionPane.showConfirmDialog(this,"Bạn có muốn cập nhật điểm không", "Cảnh báo", JOptionPane.YES_NO_OPTION);
               if(k==0){
                   ThaoTacGV.suaDiemHD(cd);
                   show();
               }
//           }
//           else{
//                int h= JOptionPane.showConfirmDialog(this,"Bạn có muốn lưu điểm không?" , "Cảnh Báo", JOptionPane.YES_NO_OPTION);
//                if(h==0){
//                   ThaoTacGV.suaDiemHD(cd);
//                   show();
//                }    
//           }  
        }
        else{
            JOptionPane.showMessageDialog(this,"Mã đồ án không tồn tại!");
        }
         //TODO add your handling code here:
    }//GEN-LAST:event_jButtonLuuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangDS;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabeltbHD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbbmadoanhd;
    private javax.swing.JTextField jtfDHD;
    // End of variables declaration//GEN-END:variables
}
