
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Acer
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public Login() {
        initComponents();
        tf_Username.setText("");
        pf_Password.setText("");
        lb_TB.setVisible(false);
    }

    public static String ma_Hoa_MK(String s) {
        Connection con = DBConnection.getConnection();
        String sql = "SELECT CONVERT(VARCHAR(32), HashBytes('MD5','" + s + "' ), 2) as md5";
        try {
            PreparedStatement p = con.prepareStatement(sql);
            ResultSet m = p.executeQuery();
            while (m.next()) {
                s = m.getString(1);
            }
            m.close();
            p.close();
        } catch (SQLException e) {
            System.err.println("Loi ma hoa mk");
        }
        return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tf_Username = new javax.swing.JTextField();
        pf_Password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tf_SignIn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_TB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(74, 31, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo_PTIT_150.png.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_Username.setBackground(new java.awt.Color(186, 79, 84));
        tf_Username.setForeground(new java.awt.Color(204, 204, 204));
        tf_Username.setText("Username");
        tf_Username.setBorder(null);
        tf_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_UsernameActionPerformed(evt);
            }
        });
        jPanel3.add(tf_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 210, 30));

        pf_Password.setBackground(new java.awt.Color(186, 79, 84));
        pf_Password.setForeground(new java.awt.Color(204, 204, 204));
        pf_Password.setText("Password");
        pf_Password.setBorder(null);
        pf_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pf_PasswordKeyPressed(evt);
            }
        });
        jPanel3.add(pf_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 210, 30));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 210, 20));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 210, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_lock_20px.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 20, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_user_20px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 20, 30));

        jPanel4.setBackground(new java.awt.Color(186, 79, 84));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        tf_SignIn.setForeground(new java.awt.Color(204, 204, 204));
        tf_SignIn.setText("           Sign In");
        tf_SignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_SignInMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tf_SignIn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tf_SignIn, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(74, 31, 61));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 0, 20, -1));

        lb_TB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TB.setForeground(new java.awt.Color(255, 255, 255));
        lb_TB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_TB.setText("Sai thông tin đăng nhập!");
        jPanel3.add(lb_TB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 320, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_UsernameActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void tf_SignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_SignInMouseClicked
        try {
            String url = "jdbc:sqlserver://;databaseName=QLDASV;user=sa;password=123";
            String sql = "select * from taikhoan where madangnhap=? and matkhau=?";
            Connection con = DriverManager.getConnection(url);
            int check = 0;
            String username = tf_Username.getText().trim();
            String password = ma_Hoa_MK(String.valueOf(pf_Password.getPassword()).trim());
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String quyen = rs.getString("maphanquyen");
                switch (quyen.trim()) {
                    case "0":
                        dispose();
                        Admin f_Admin = new Admin();
                        check = 1;
                        //f_Admin.setTitle("Admin");
                        //f_Admin.setLocationRelativeTo(this);
                        //f_Admin.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        this.setUndecorated(true);
                        f_Admin.setVisible(true);
                        break;
                    case "1":
                        dispose();
                        GiangVien_Form.ma = tf_Username.getText().toString();
                        GiangVien_Form f_GV = new GiangVien_Form();
                        check = 1;
                        f_GV.setTitle("Giang Vien");
                        f_GV.setVisible(true);
                        f_GV.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        break;
                    case "2":
                        dispose();
                        SinhVien_Form.ma = tf_Username.getText().toString();

                        SinhVien_Form f_SV = new SinhVien_Form();
                        check = 1;
                        f_SV.setTitle("Sinh Vien");
                        f_SV.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        f_SV.jLabel_masv.setText(rs.getString(1));
                        f_SV.setVisible(true);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "User name and password do"
                                + " not match!", "ALERT!",
                                JOptionPane.ERROR_MESSAGE);
                        break;
                }
            }
            if (check == 0) {
                lb_TB.setVisible(true);
            }
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_tf_SignInMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked

    }//GEN-LAST:event_jPanel4MouseClicked

    //Nhan Enter de dang nhap thay vi ban Login
    private void pf_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_PasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String url = "jdbc:sqlserver://;databaseName=QLDASV;user=sa;password=123";
                String sql = "select * from taikhoan where madangnhap=? and matkhau=?";
                Connection con = DriverManager.getConnection(url);
                int check = 0;
                String username = tf_Username.getText();
                String password = ma_Hoa_MK(String.valueOf(pf_Password.getPassword()).trim());
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, username);
                ps.setString(2, password);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
//                    String taiKhoan= rs.getString("madangnhap");
//                    String matKhau= rs.getString("matkhau");
                    String quyen = rs.getString("maphanquyen");
                    //if((username.equals(taiKhoan)) && (password.equals(matKhau))){
                    //System.out.println("Q|"+quyen+"|O");
                    switch (quyen.trim()) {
                        case "0":
                            dispose();
                            Admin f_Admin = new Admin();
                            check = 1;
                            //f_Admin.setTitle("Admin");
                            //f_Admin.setLocationRelativeTo(this);
                            //f_Admin.setExtendedState(JFrame.MAXIMIZED_BOTH);
                            this.setUndecorated(true);
                            f_Admin.setVisible(true);
                            break;
                        case "1":
                            dispose();
                            GiangVien_Form.ma = tf_Username.getText().toString();
                            GiangVien_Form f_GV = new GiangVien_Form();
                            check = 1;
                            f_GV.setTitle("Giang Vien");
                            f_GV.setVisible(true);
                            f_GV.setExtendedState(JFrame.MAXIMIZED_BOTH);
                            break;
                        case "2":
                            dispose();
                            SinhVien_Form.ma = tf_Username.getText().toString();

                            SinhVien_Form f_SV = new SinhVien_Form();
                            check = 1;
                            f_SV.setTitle("Sinh Vien");
                            f_SV.setExtendedState(JFrame.MAXIMIZED_BOTH);
                            f_SV.jLabel_masv.setText(rs.getString(1));
                            f_SV.setVisible(true);
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "User name and password do"
                                    + " not match!", "ALERT!",
                                    JOptionPane.ERROR_MESSAGE);
                            break;
                    }

                }
                if (check == 0) {
                    lb_TB.setVisible(true);
                }
            } catch (SQLException | HeadlessException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_pf_PasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lb_TB;
    private javax.swing.JPasswordField pf_Password;
    private javax.swing.JLabel tf_SignIn;
    public javax.swing.JTextField tf_Username;
    // End of variables declaration//GEN-END:variables
}
